In [27]:
# ============================================================
# dask_pipeline.ipynb
# Dask ML Pipeline - NYC Taxi Dataset
# ============================================================

# 1. Imports

import time

import requests
import dask.dataframe as dd
import numpy as np
import pandas as pd

from pydantic import ByteSize
from dask.distributed import Client
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from dask_ml.model_selection import KFold, train_test_split
from sklearn.metrics import make_scorer

from dask_ml.model_selection import train_test_split
from dask_ml.linear_model import LogisticRegression as DaskLogisticRegression
from xgboost.dask import DaskXGBRegressor

In [47]:
# 2. Start Dask client

client = Client()

client

/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/distributed/node.py:188: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 63110 instead
  warnings.warn(

In [50]:
# 3. Configuration

RUN_MODE = "local"

if RUN_MODE == "local":
    DATA_PATH = "../data/raw/taxi/yellow_tripdata_2026-01.parquet"
else:
    DATA_PATH = "gs://your-bucket/taxi/yellow_tripdata_2026-01.parquet"

LOOKUP_PATH = "../data/raw/taxi/taxi_zone_lookup.csv"

SOURCE_URL = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2026-01.parquet"

TARGET = "fare_amount"

FEATURES = [
    "trip_distance",
    "passenger_count",
    "PULocationID",
    "DOLocationID",
    "payment_type",
]

SEED = 42
TEST_SIZE = 0.2

CLASSIFICATION_CV_FOLDS = 4
REGRESSION_CV_FOLDS = 5

LOGISTIC_MAX_ITER = 500
LOGISTIC_REGULARIZATION = 0.0

XGB_N_ESTIMATORS = 100
XGB_MAX_DEPTH = 6

XGB_LEARNING_RATE = 0.1

In [31]:
from collections.abc import Generator
from contextlib import contextmanager
from datetime import timedelta
from pathlib import Path
from time import perf_counter
from typing import TypedDict

class Duration(TypedDict):
    duration: timedelta


def _mem_str(path: str) -> str:
    path = Path(path)
    size = path.stat().st_size
    return ByteSize(size).human_readable(decimal=True)

@contextmanager
def timeit(name: str) -> Generator[dict]:
    result = {"duration": timedelta()}
    start_time = perf_counter()
    yield result
    end_time = perf_counter()
    duration = timedelta(seconds=end_time - start_time)
    print(f"{name} took {duration}")
    result["duration"] = duration

In [32]:
from datetime import timedelta

# 4. Load data
df: dd.DataFrame = None
try:
    with timeit("Loading data"):
        df = dd.read_parquet(DATA_PATH)
except FileNotFoundError:
    response = requests.get(SOURCE_URL)
    response.raise_for_status()
    Path(DATA_PATH).parent.mkdir(parents=True, exist_ok=True)
    with open(DATA_PATH, "wb") as f:
        f.write(response.content)
    print(f"Downloaded {DATA_PATH}, {_mem_str(DATA_PATH)}")


if df is None:
    with timeit("Loading data"):
        df = dd.read_parquet(DATA_PATH)

location_lookup = dd.read_csv("../data/raw/taxi/taxi_zone_lookup.csv")

df.head()

Loading data took 0:00:00.009850

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.90,1.0,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.40,1.0,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0.0,2.16,1.0,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1.0,23.10,2.5,0.0,0.75

In [33]:
# 5. Basic dataset inspection

print("Columns:")
print(df.columns)

print("Dtypes:")
print(df.dtypes)

print("Number of partitions:")
print(df.npartitions)

Columns:
Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee'],
      dtype='str')
Dtypes:
VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                   int64
trip_distance                   float64
RatecodeID                        int64
store_and_fwd_flag               string
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
dtype: object
Number of partitions:
1

In [34]:
# 6. Preprocessing

df = df[FEATURES + [TARGET]]
df = df.dropna()
df = df[
    (df["fare_amount"] > 0) &
    (df["trip_distance"] > 0) &
    (df["passenger_count"] > 0)
]
df.tail()

,trip_distance,passenger_count,PULocationID,DOLocationID,payment_type,fare_amount
2636822,2.75,2.0,166,237,1,17.0
2636827,1.86,1.0,230,239,1,12.1
2636828,2.66,1.0,239,262,1,16.3
2636829,0.36,4.0,170,170,1,5.8
2636830,1.15,1.0,230,229,1,10.7

In [35]:
def benchmark_dask(data_path, lookup_path):
    metrics = {}

    # 1. Read Data
    with timeit("1. Read Data") as duration:
        df = dd.read_parquet(data_path)
        df_lookup = dd.read_csv(lookup_path)
        df_lookup["LocationID"] = df_lookup["LocationID"].astype(df["PULocationID"].dtype)
        # Dask reads lazily; force compute on length to evaluate reading execution
        _ = len(df)
    metrics['1. Read Data'] = duration["duration"]

    # 2. Count Index (Simple count)
    with timeit("2. Count Operation") as duration:
        _ = df.count().compute()
    metrics['2. Count Operation'] = duration["duration"]

    # 3. Complex Arithmetic Formula
    with timeit("3. Complex Arithmetic") as duration:
        arithmetic_res = (df['fare_amount'] + df['tip_amount']) * 1.5 / (df['passenger_count'] + 1)
        _ = arithmetic_res.compute()
    metrics['3. Complex Arithmetic'] = duration["duration"]

    # 4. Statistical Standard Deviation
    with timeit("4. Standard Deviation") as duration:
        _ = df['trip_distance'].std().compute()
    metrics['4. Standard Deviation'] = duration["duration"]

    # 5. GroupBy Aggregation
    with timeit("5. GroupBy Mean") as duration:
        _ = df.groupby('passenger_count')['fare_amount'].mean().compute()
    metrics['5. GroupBy Mean'] = duration["duration"]

    # 6. Merge/Join with Count
    with timeit("6. Join & Count") as duration:
        joined = dd.merge(df, df_lookup, left_on='PULocationID', right_on='LocationID', how='inner')
        _ = len(joined)
    metrics['6. Join & Count'] = duration["duration"]

    return metrics

In [36]:
benchmarks = benchmark_dask(DATA_PATH, LOOKUP_PATH)

1. Read Data took 0:00:00.019699
2. Count Operation took 0:00:00.453232
3. Complex Arithmetic took 0:00:00.132646
4. Standard Deviation took 0:00:00.052319
5. GroupBy Mean took 0:00:00.109154
6. Join & Count took 0:00:00.918938

In [37]:
from pathlib import Path

yellow2025: dd.DataFrame = None
for taxi_file in Path("../data/raw/taxi").glob("yellow*.parquet"):
    yellow = dd.read_parquet(taxi_file)
    yellow2025 = dd.concat([yellow2025, yellow]) if yellow2025 is not None else yellow

yellow2025.to_parquet("../data/raw/taxi/2025_yellow_tripdata.parquet", write_index=False)

In [38]:
benchmarks = benchmark_dask("../data/raw/taxi/2025_yellow_tripdata.parquet", LOOKUP_PATH)

1. Read Data took 0:00:00.059529
2. Count Operation took 0:00:00.303590
3. Complex Arithmetic took 0:00:00.121337
4. Standard Deviation took 0:00:00.049113
5. GroupBy Mean took 0:00:00.100635
6. Join & Count took 0:00:00.142539

In [39]:
X = df[FEATURES]
y_reg = df[TARGET]

In [42]:
X_train, X_test, y_train_reg, y_test_reg = train_test_split(

    X,
    y_reg,
    test_size=TEST_SIZE,
    random_state=SEED,
    shuffle=True

)

reg_model = DaskXGBRegressor(

    n_estimators=XGB_N_ESTIMATORS,
    max_depth=XGB_MAX_DEPTH,
    learning_rate=XGB_LEARNING_RATE,
    objective="reg:squarederror",
    random_state=SEED

)

reg_cv = KFold(

    n_splits=REGRESSION_CV_FOLDS,
    shuffle=True,
    random_state=SEED

)

# Cross-validation
reg_cv_rmse_scores = []

with timeit("Regression cross-validation") as duration:
    train_data = X_train.assign(**{TARGET: y_train_reg})
    train_data = train_data.reset_index(drop=True)

    train_data = train_data.assign(
        cv_fold=(train_data.index % REGRESSION_CV_FOLDS)
    )

    for fold in range(REGRESSION_CV_FOLDS):
        fold_train = train_data[train_data["cv_fold"] != fold]
        fold_val = train_data[train_data["cv_fold"] == fold]

        X_fold_train = fold_train[FEATURES]
        y_fold_train = fold_train[TARGET]

        X_fold_val = fold_val[FEATURES]
        y_fold_val = fold_val[TARGET]

        fold_model = DaskXGBRegressor(
            n_estimators=XGB_N_ESTIMATORS,
            max_depth=XGB_MAX_DEPTH,
            learning_rate=XGB_LEARNING_RATE,
            objective="reg:squarederror",
            random_state=SEED,
        )

        fold_model.fit(X_fold_train, y_fold_train)

        y_fold_pred = fold_model.predict(X_fold_val).compute()
        y_fold_val_local = y_fold_val.compute()

        fold_rmse = mean_squared_error(
            y_fold_val_local,
            y_fold_pred
        ) ** 0.5

        reg_cv_rmse_scores.append(fold_rmse)

regression_cv_time = duration["duration"]
regression_cv_rmse_mean = np.mean(reg_cv_rmse_scores)
regression_cv_rmse_std = np.std(reg_cv_rmse_scores)

print("Regression CV RMSE scores:", reg_cv_rmse_scores)
print("Mean RMSE:", regression_cv_rmse_mean)
print("Std RMSE:", regression_cv_rmse_std)

with timeit("Regression training") as duration:
    fitted_reg_model = reg_model.fit(
        X_train,
        y_train_reg
    )

regression_train_time = duration["duration"]

with timeit("Regression prediction") as duration:
    y_pred_reg = fitted_reg_model.predict(X_test).compute()

regression_prediction_time = duration["duration"]

y_test_reg_local = y_test_reg.compute()

[10:06:32] Task [xgboost.dask-2]:tcp://127.0.0.1:62428 got rank 0
[10:06:36] Task [xgboost.dask-2]:tcp://127.0.0.1:62428 got rank 0
[10:06:46] Task [xgboost.dask-2]:tcp://127.0.0.1:62428 got rank 0
[10:06:51] Task [xgboost.dask-2]:tcp://127.0.0.1:62428 got rank 0
[10:06:55] Task [xgboost.dask-2]:tcp://127.0.0.1:62428 got rank 0

Regression cross-validation took 0:00:27.983330
Regression CV RMSE scores: [6.320894720842316, 6.483134821856233, 7.306526914611537, 6.292044816274079, 6.295921874044099]
Mean RMSE: 6.539704629525652
Std RMSE: 0.3898357990621398

[10:07:00] Task [xgboost.dask-2]:tcp://127.0.0.1:62428 got rank 0

Regression training took 0:00:02.919167
Regression prediction took 0:00:00.416854

In [43]:
regression_results = {
    "library": "Dask",
    "task": "regression",
    "model": "DaskXGBRegressor",
    "cv_folds": REGRESSION_CV_FOLDS,
    "cv_time": regression_cv_time,
    "cv_rmse_mean": regression_cv_rmse_mean,
    "cv_rmse_std": regression_cv_rmse_std,
    "train_time": regression_train_time,
    "prediction_time": regression_prediction_time,
    "mae": mean_absolute_error(y_test_reg_local, y_pred_reg),
    "mse": mean_squared_error(y_test_reg_local, y_pred_reg),
    "rmse": mean_squared_error(y_test_reg_local, y_pred_reg) ** 0.5,
    "r2": r2_score(y_test_reg_local, y_pred_reg),
}

In [ ]:
def classify_fare_partition(partition):
    return partition.assign(
        fare_class=np.select(
            [
                partition[TARGET] < 15,
                partition[TARGET] < 40,
            ],
            [0, 1],
            default=2
        )
    )


df_cls = df.map_partitions(classify_fare_partition)

X_cls = df_cls[FEATURES]
y_cls = df_cls["fare_class"]

X_train, X_test, y_train_cls, y_test_cls = train_test_split(
    X_cls,
    y_cls,
    test_size=TEST_SIZE,
    random_state=SEED,
    shuffle=True
)

X_train_arr = X_train.to_dask_array(lengths=True)
X_test_arr = X_test.to_dask_array(lengths=True)

y_train_arr = y_train_cls.to_dask_array(lengths=True)
y_test_arr = y_test_cls.to_dask_array(lengths=True)

cls_model = DaskLogisticRegression(
    max_iter=LOGISTIC_MAX_ITER,
    fit_intercept=True
)

#Cross Validation Models
cls_cv = KFold(

    n_splits=CLASSIFICATION_CV_FOLDS,
    shuffle=True,
    random_state=SEED

)

cls_cv_f1_scores = []

with timeit("Classification cross-validation") as duration:

    for train_idx, val_idx in cls_cv.split(X_train_arr):

        X_fold_train = X_train_arr[train_idx]
        X_fold_val = X_train_arr[val_idx]
        y_fold_train = y_train_arr[train_idx]
        y_fold_val = y_train_arr[val_idx]

        fold_model = DaskLogisticRegression(

            max_iter=LOGISTIC_MAX_ITER,
            fit_intercept=True

        )

        fold_model.fit(X_fold_train, y_fold_train)
        y_fold_pred = fold_model.predict(X_fold_val).compute()
        y_fold_val_local = y_fold_val.compute()

        fold_f1 = f1_score(

            y_fold_val_local,
            y_fold_pred,
            average="macro"

        )

        cls_cv_f1_scores.append(fold_f1)

classification_cv_time = duration["duration"]
classification_cv_f1_mean = np.mean(cls_cv_f1_scores)
classification_cv_f1_std = np.std(cls_cv_f1_scores)

print("Classification CV F1 scores:", cls_cv_f1_scores)
print("Mean F1:", classification_cv_f1_mean)
print("Std F1:", classification_cv_f1_std) 

with timeit("Classification training") as duration:
    fitted_cls_model = cls_model.fit(X_train_arr, y_train_arr)

classification_train_time = duration["duration"]

with timeit("Classification prediction") as duration:
    y_pred_cls = fitted_cls_model.predict(X_test_arr).compute()

classification_prediction_time = duration["duration"]

y_test_cls_local = y_test_arr.compute()

/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)

In [ ]:
classification_results = {
    "library": "Dask",
    "task": "classification",
    "model": "DaskLogisticRegression",
    "cv_folds": CLASSIFICATION_CV_FOLDS,
    "cv_time": classification_cv_time,
    "cv_f1_macro_mean": classification_cv_f1_mean,
    "cv_f1_macro_std": classification_cv_f1_std,
    "train_time": classification_train_time,
    "prediction_time": classification_prediction_time,
    "accuracy": accuracy_score(y_test_cls_local, y_pred_cls),
    "precision_macro": precision_score(y_test_cls_local, y_pred_cls, average="macro"),
    "recall_macro": recall_score(y_test_cls_local, y_pred_cls, average="macro"),
    "f1_macro": f1_score(y_test_cls_local, y_pred_cls, average="macro"),
}

/Users/gustavooliveira/WORKSPACE - 2025-2026/FCUP/Segundo-Semestre/BigData-CloudComputing/Part2/Project/venv-bdcc/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [ ]:
#Save Results 

benchmark_results_df = pd.DataFrame([
    {
        "library": "Dask",
        "operation": operation,
        "duration": duration,
        "duration_seconds": duration.total_seconds()
    }

    for operation, duration in benchmarks.items()
])

benchmark_results_df.to_csv("../results/One-Month/dask_benchmark_results.csv",index=False)

results_df = pd.DataFrame([
    regression_results,
    classification_results
])

results_df.to_csv("../results/One-Month/dask_pipeline_results.csv", index=False)

results_df

,library,task,model,train_time,prediction_time,mae,mse,rmse,r2,accuracy,precision_macro,recall_macro,f1_macro
0,Dask,regression,DaskXGBRegressor,0 days 00:00:03.000190,0 days 00:00:00.416417,2.782677,38.175703,6.178649,0.886141,NaN,NaN,NaN,NaN
1,Dask,classification,DaskLogisticRegression,0 days 00:00:06.261503,0 days 00:00:01.026901,NaN,NaN,NaN,NaN,0.768858,0.496506,0.567697,0.525652